<?php
/**
 * Plugin functions.
 *
 * @package PublicCollaboration
 */

declare(strict_types = 1);

namespace PublicCollaboration;

use WP_Error;
use WP_Post;
use WP_Post_Type;
use WP_Query;
use WP_REST_Request;
use WP_User;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Registers the collaboration request post type.
 *
 * The post type is not public and has no admin UI. It exists only so that each
 * collaboration request gets a URL, a slug to act as the token, an author, and
 * a parent — the post being collaborated on.
 *
 * @return void
 */
function register_post_type(): void {
	\register_post_type(
		Collaboration_Request::POST_TYPE,
		[
			'labels'              => [
				'name'          => _x( 'Collaboration Requests', 'post type general name', 'public-collaboration' ),
				'singular_name' => _x( 'Collaboration Request', 'post type singular name', 'public-collaboration' ),
			],
			'supports'            => [ 'author' ],
			'rewrite'             => [
				/**
				 * Filters the URL prefix of the collaboration link.
				 *
				 * @param string $slug URL prefix. Default 'collaborate'.
				 */
				'slug'       => apply_filters( 'public_collaboration_rewrite_slug', 'collaborate' ),
				'with_front' => false,
				'feeds'      => false,
				'pages'      => false,
			],
			'public'              => false,
			'publicly_queryable'  => true,
			'show_ui'             => false,
			'show_in_menu'        => false,
			'show_in_rest'        => false,
			'has_archive'         => false,
			'can_export'          => false,
			'exclude_from_search' => true,
			'delete_with_user'    => true,

			/*
			 * Without this, a site on plain permalinks would address the
			 * collaboration page as `?post_type=…&p=123` — a guessable post ID
			 * standing in for an unguessable token. With it, the token is in the
			 * URL either way.
			 */
			'query_var'           => Collaboration_Request::POST_TYPE,
		]
	);
}

/**
 * Registers the REST API routes.
 *
 * @return void
 */
function register_rest_routes(): void {
	$controller = new REST_Collaboration_Requests_Controller();
	$controller->register_routes();
}

/**
 * Registers the plugin's scripts and styles.
 *
 * @return void
 */
function register_assets(): void {
	foreach ( [ 'editor', 'welcome' ] as $handle ) {
		$asset = get_asset_meta( $handle );

		wp_register_script(
			"public-collaboration-$handle",
			plugins_url( "build/$handle.js", PUBLIC_COLLABORATION_FILE ),
			$asset['dependencies'],
			$asset['version'],
			[ 'strategy' => 'defer' ]
		);

		wp_set_script_translations( "public-collaboration-$handle", 'public-collaboration' );

		wp_register_style(
			"public-collaboration-$handle",
			plugins_url( "build/$handle.css", PUBLIC_COLLABORATION_FILE ),
			[ 'wp-components' ],
			$asset['version']
		);

		wp_style_add_data( "public-collaboration-$handle", 'rtl', 'replace' );
	}
}

/**
 * Returns the build metadata for a given entry point.
 *
 * @param string $handle Entry point name.
 * @return array{dependencies: string[], version: string} Asset metadata.
 */
function get_asset_meta( string $handle ): array {
	$asset_file = PUBLIC_COLLABORATION_DIR . "/build/$handle.asset.php";

	/**
	 * Asset metadata as generated by the build.
	 *
	 * @var array{dependencies?: string[], version?: string} $asset
	 */
	$asset = is_readable( $asset_file ) ? require $asset_file : [];

	return [
		'dependencies' => $asset['dependencies'] ?? [],
		'version'      => $asset['version'] ?? VERSION,
	];
}

/**
 * Enqueues the editor integration.
 *
 * Two sides of the same feature, and never both at once: whoever is sharing the
 * post gets the panel that mints links, and whoever followed one gets the
 * greeting that explains where they have landed.
 *
 * @return void
 */
function enqueue_block_editor_assets(): void {
	$request = Collaboration_Request::get_for_user( get_current_user_id() );

	if ( $request instanceof Collaboration_Request ) {
		wp_enqueue_script( 'public-collaboration-welcome' );
		wp_enqueue_style( 'public-collaboration-welcome' );

		wp_add_inline_script(
			'public-collaboration-welcome',
			sprintf( 'window.publicCollaboration = %s;', wp_json_encode( get_collaborator_data( $request ) ) ),
			'before'
		);

		return;
	}

	if ( ! current_user_can( 'edit_posts' ) ) {
		return;
	}

	wp_enqueue_script( 'public-collaboration-editor' );
	wp_enqueue_style( 'public-collaboration-editor' );
}

/**
 * Returns the data the collaborator's greeting needs, ready to be handed to the browser.
 *
 * Printed with the page rather than fetched: the greeting is the first thing
 * that happens, and it should not be preceded by a spinner.
 *
 * @param Collaboration_Request $request The collaboration request.
 * @return array Collaborator data.
 *
 * @phpstan-return array<string, mixed>
 */
function get_collaborator_data( Collaboration_Request $request ): array {
	$author = get_userdata( $request->get_author_id() );
	$parent = $request->get_parent();
	$user   = wp_get_current_user();

	$title = $parent instanceof WP_Post ? get_the_title( $parent ) : '';

	return [
		'postId'      => $request->get_parent_id(),
		'postTitle'   => '' !== $title ? $title : __( '(no title)', 'public-collaboration' ),
		'sharedBy'    => $author instanceof WP_User ? $author->display_name : '',
		'displayName' => $user->display_name,
		'expiresAt'   => $request->get_expires_at(),
		'canEdit'     => $request->allows( Collaboration_Request::CAP_EDIT ),
		'canUpload'   => $request->allows( Collaboration_Request::CAP_UPLOAD ),
	];
}

/**
 * Returns the URL of the block editor for a given post.
 *
 * Not get_edit_post_link(): that returns nothing unless the current user can
 * already edit the post, and the whole point of the redirect it is needed for
 * is to get them to the screen where they can.
 *
 * @param int $post_id Post ID.
 * @return string Admin URL of the editor.
 */
function get_editor_url( int $post_id ): string {
	$post      = get_post( $post_id );
	$post_type = $post instanceof WP_Post ? get_post_type_object( $post->post_type ) : null;

	if ( $post_type instanceof WP_Post_Type && ! empty( $post_type->_edit_link ) ) {
		return admin_url( sprintf( $post_type->_edit_link . '&action=edit', $post_id ) );
	}

	return admin_url( sprintf( 'post.php?post=%d&action=edit', $post_id ) );
}

/**
 * Filters the template used for the collaboration page.
 *
 * Following a valid link is the whole interaction: the visitor is signed in as
 * the collaborator and sent straight to the editor. The template is only ever
 * reached when that cannot happen, and exists to say why.
 *
 * @param string $template Template path.
 * @return string Filtered template path.
 */
function filter_template_include( string $template ): string {
	if ( ! is_singular( Collaboration_Request::POST_TYPE ) ) {
		return $template;
	}

	$post = get_queried_object();

	/*
	 * WordPress will happily resolve any publicly queryable post by its ID.
	 * The whole security model here rests on the token being unguessable, so a
	 * page reached by a post ID rather than by following the link is a 404 —
	 * otherwise counting upwards from 1 would find every live collaboration
	 * request.
	 */
	$name = get_query_var( 'name' );

	if ( ! $post instanceof WP_Post || ! is_string( $name ) || $name !== $post->post_name ) {
		global $wp_query;

		if ( $wp_query instanceof WP_Query ) {
			$wp_query->set_404();
		}

		status_header( 404 );
		nocache_headers();

		return get_404_template();
	}

	// A page carrying a live token has no business being indexed or cached.
	if ( ! headers_sent() ) {
		header( 'X-Robots-Tag: noindex, nofollow', true );
	}

	nocache_headers();

	$request = Collaboration_Request::from_post( $post );

	if ( ! $request instanceof Collaboration_Request ) {
		return get_404_template();
	}

	/**
	 * Filters the template used to render the collaboration page.
	 *
	 * @param string $template Absolute path to the template file.
	 */
	$template = (string) apply_filters(
		'public_collaboration_template',
		PUBLIC_COLLABORATION_DIR . '/templates/collaboration-page.php'
	);

	$parent = $request->get_parent();

	if ( $request->is_expired() || ! $parent instanceof WP_Post ) {
		status_header( 410 );

		return $template;
	}

	// Whoever shared the link, following their own link. Nothing to sign in as.
	if ( current_user_can( 'edit_post', $parent->ID ) ) {
		wp_safe_redirect( get_editor_url( $parent->ID ) );
		exit;
	}

	/*
	 * Somebody else's session. Swapping it out from under them would sign them
	 * out of their own account without asking, so the page offers the choice
	 * instead.
	 */
	if ( is_user_logged_in() && get_current_user_id() !== $request->get_user_id() ) {
		status_header( 403 );

		return $template;
	}

	$user_id = $request->get_or_create_user();

	if ( is_wp_error( $user_id ) ) {
		status_header( 500 );

		return $template;
	}

	$user = get_userdata( $user_id );

	if ( ! $user instanceof WP_User ) {
		status_header( 500 );

		return $template;
	}

	wp_set_current_user( $user_id );
	wp_set_auth_cookie( $user_id );

	/** This action is documented in wp-includes/user.php */
	do_action( 'wp_login', $user->user_login, $user ); // phpcs:ignore WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedHooknameFound

	wp_safe_redirect( get_editor_url( $parent->ID ) );
	exit;
}

/**
 * Grants a collaborator the capabilities their link was shared with.
 *
 * Nothing is written to the user's own capabilities: every grant below applies
 * to the single check being made, and is worked out again from the request the
 * next time one is made. Let the link expire and the account, still roleless,
 * can do nothing at all.
 *
 * @param array    $allcaps Array of key/value pairs where keys represent a capability name
 *                          and boolean values represent whether the user has that capability.
 * @param string[] $caps    Primitive capabilities required of the user.
 * @param array    $args    Arguments that accompany the requested capability check.
 * @param WP_User  $user    The user object.
 * @return array Filtered capabilities.
 *
 * @phpstan-param array<string, bool> $allcaps
 * @phpstan-param array<int, mixed> $args
 * @phpstan-return array<string, bool>
 */
function filter_user_has_cap( array $allcaps, array $caps, array $args, $user ): array {
	if ( ! $user instanceof WP_User ) {
		return $allcaps;
	}

	$request = Collaboration_Request::get_for_user( $user->ID );

	if ( ! $request instanceof Collaboration_Request ) {
		return $allcaps;
	}

	$parent = $request->get_parent();

	if ( ! $parent instanceof WP_Post ) {
		return $allcaps;
	}

	$post_type = get_post_type_object( $parent->post_type );

	if ( ! $post_type instanceof WP_Post_Type ) {
		return $allcaps;
	}

	// Enough to be let into wp-admin at all.
	$allcaps['read'] = true;

	/*
	 * The editor will not render until it has read the post type in `edit`
	 * context, and that check is the bare `edit_posts` capability with no post
	 * attached — there is no post ID to scope it to. On its own it grants very
	 * little: editing anybody else's post additionally needs
	 * `edit_others_posts`, which is only ever granted below, for this one post.
	 * What it would otherwise allow is creating posts, and the two ways to do
	 * that are closed off in filter_rest_pre_insert() and
	 * restrict_admin_access().
	 */
	$allcaps[ $post_type->cap->edit_posts ] = true;

	if ( $request->allows( Collaboration_Request::CAP_UPLOAD ) ) {
		$allcaps['upload_files'] = true;
	}

	$meta_cap  = isset( $args[0] ) && \is_string( $args[0] ) ? $args[0] : '';
	$object_id = isset( $args[2] ) && is_numeric( $args[2] ) ? (int) $args[2] : 0;

	if ( $object_id !== $parent->ID ) {
		return $allcaps;
	}

	$allowed = [ 'read_post' ];

	if ( $request->allows( Collaboration_Request::CAP_EDIT ) ) {
		array_push( $allowed, 'edit_post', 'add_post_meta', 'edit_post_meta', 'delete_post_meta' );
	}

	if ( ! \in_array( $meta_cap, $allowed, true ) ) {
		return $allcaps;
	}

	/*
	 * `$caps` is whatever map_meta_cap() worked out this particular check needs
	 * — `edit_others_posts` and `edit_published_posts` for someone else's
	 * published post, something shorter for a draft. Granting exactly that set,
	 * for exactly this check, is what keeps the grant tied to one post.
	 *
	 * Except for `do_not_allow`, which map_meta_cap() returns as its way of
	 * saying no outright. Granting it would turn every refusal into a yes.
	 */
	foreach ( $caps as $cap ) {
		if ( 'do_not_allow' === $cap ) {
			continue;
		}

		$allcaps[ (string) $cap ] = true;
	}

	return $allcaps;
}

/**
 * Keeps collaborators on the post they were invited to.
 *
 * They hold `edit_posts` for the editor's sake (see filter_user_has_cap()),
 * which would otherwise be enough to reach the rest of wp-admin.
 *
 * @return void
 */
function restrict_admin_access(): void {
	// Uploads and the editor's own background requests come through here too.
	if ( wp_doing_ajax() || wp_is_serving_rest_request() ) {
		return;
	}

	$request = Collaboration_Request::get_for_user( get_current_user_id() );

	if ( ! $request instanceof Collaboration_Request ) {
		return;
	}

	$post_id = $request->get_parent_id();

	global $pagenow;

	if ( 'post.php' === $pagenow ) {
		// phpcs:ignore WordPress.Security.NonceVerification.Recommended
		$requested = isset( $_GET['post'] ) && is_numeric( $_GET['post'] ) ? (int) $_GET['post'] : 0;

		if ( $requested === $post_id ) {
			return;
		}
	}

	wp_safe_redirect( get_editor_url( $post_id ) );
	exit;
}

/**
 * Keeps core's post lock out of the way of a collaboration session.
 *
 * The lock exists to stop two people silently overwriting each other, and it
 * answers that by letting only one of them in. Sharing a post is a decision to
 * have two people in it, so for a collaborator the lock has nothing useful left
 * to say: it would greet them with "somebody else is editing" and, a heartbeat
 * later, tell one of the two that the other had taken over.
 *
 * @param bool $show Whether to show the dialog.
 * @return bool Filtered value.
 */
function filter_show_post_locked_dialog( bool $show ): bool {
	if ( Collaboration_Request::get_for_user( get_current_user_id() ) instanceof Collaboration_Request ) {
		return false;
	}

	return $show;
}

/**
 * Stops a collaborator taking the post lock.
 *
 * Whoever shared the post keeps it. Without this the collaborator would claim
 * the lock on arrival, and the person who invited them would be the one told
 * that somebody else is editing.
 *
 * @param mixed  $check     Whether to allow updating metadata. Null unless something short-circuits it.
 * @param int    $object_id ID of the object the metadata is for.
 * @param string $meta_key  Metadata key.
 * @return mixed Null to go ahead with the update, anything else to skip it.
 */
function filter_post_lock_meta( $check, int $object_id, string $meta_key ) {
	if ( '_edit_lock' !== $meta_key ) {
		return $check;
	}

	if ( ! Collaboration_Request::get_for_user( get_current_user_id() ) instanceof Collaboration_Request ) {
		return $check;
	}

	// Reported as done, so that nothing upstream treats it as a failure.
	return true;
}

/**
 * Stops the heartbeat telling a collaborator that somebody has taken over.
 *
 * @return void
 */
function unhook_post_lock_heartbeat(): void {
	if ( ! Collaboration_Request::get_for_user( get_current_user_id() ) instanceof Collaboration_Request ) {
		return;
	}

	remove_filter( 'heartbeat_received', 'wp_refresh_post_lock', 10 );
}

/**
 * Registers the guard that stops collaborators creating posts over the REST API.
 *
 * Attachments are left out on purpose — uploading is one of the things a link
 * can be shared for, and it is gated on the `upload_files` capability instead.
 *
 * @return void
 */
function register_rest_guards(): void {
	foreach ( get_post_types( [ 'show_in_rest' => true ], 'objects' ) as $post_type ) {
		if ( 'attachment' === $post_type->name ) {
			// Creating one is what uploading *is*, and it is gated on a
			// capability instead. Listing them still needs narrowing.
			add_filter( 'rest_attachment_query', __NAMESPACE__ . '\filter_rest_attachment_query', 10, 2 );

			continue;
		}

		add_filter( "rest_pre_insert_{$post_type->name}", __NAMESPACE__ . '\filter_rest_pre_insert', 10, 2 );
		add_filter( "rest_{$post_type->name}_query", __NAMESPACE__ . '\filter_rest_query', 10, 2 );
	}
}

/**
 * Keeps a collaborator's `edit` context media to what they uploaded themselves.
 *
 * Listing media in `edit` context is gated on the same `edit_posts` capability
 * the editor cannot start without, so without this a fifteen-minute guest could
 * page through the whole media library. Their own uploads are what they need to
 * finish the job; media already in the post arrives with the post's content, not
 * from a listing.
 *
 * @param array           $args    Query arguments.
 * @param WP_REST_Request $request Request object.
 * @return array Filtered query arguments.
 *
 * @phpstan-param array<string, mixed> $args
 * @phpstan-return array<string, mixed>
 */
function filter_rest_attachment_query( array $args, $request ): array {
	if ( 'edit' !== $request['context'] ) {
		return $args;
	}

	if ( ! Collaboration_Request::get_for_user( get_current_user_id() ) instanceof Collaboration_Request ) {
		return $args;
	}

	$args['author'] = get_current_user_id();

	return $args;
}

/**
 * Keeps a collaborator's `edit` context to the post they were invited to.
 *
 * `edit_posts` is granted site-wide because the editor cannot start without it
 * (see filter_user_has_cap()), and core reads that same capability as
 * permission to list posts in `edit` context. That context carries `raw`
 * fields, which for a password-protected post is the body behind the password —
 * published, so the usual per-post read check waves it through.
 *
 * Narrowing the query rather than filtering the response: whatever core adds to
 * `edit` context later cannot leak through a collection that can only ever
 * return the one post. `view` context is left alone, so anything a logged-out
 * visitor could see is still there.
 *
 * @param array           $args    Query arguments.
 * @param WP_REST_Request $request Request object.
 * @return array Filtered query arguments.
 *
 * @phpstan-param array<string, mixed> $args
 * @phpstan-return array<string, mixed>
 */
function filter_rest_query( array $args, $request ): array {
	if ( 'edit' !== $request['context'] ) {
		return $args;
	}

	$collaboration_request = Collaboration_Request::get_for_user( get_current_user_id() );

	if ( ! $collaboration_request instanceof Collaboration_Request ) {
		return $args;
	}

	$args['post__in'] = [ $collaboration_request->get_parent_id() ];

	return $args;
}

/**
 * Stops a collaborator creating new posts.
 *
 * `edit_posts` is also what WordPress checks before letting somebody create a
 * post, and the editor needs it granted (see filter_user_has_cap()). Updates
 * arrive here carrying the ID of the post being changed; a create does not,
 * which is the difference this leans on.
 *
 * @param object          $prepared_post An object representing a single post prepared for inserting or updating the database.
 * @param WP_REST_Request $request       Request object.
 * @return object|WP_Error The post, or an error if a collaborator is trying to create one.
 */
function filter_rest_pre_insert( $prepared_post, $request ) {
	if ( ! empty( $prepared_post->ID ) ) {
		return $prepared_post;
	}

	if ( ! Collaboration_Request::get_for_user( get_current_user_id() ) instanceof Collaboration_Request ) {
		return $prepared_post;
	}

	return new WP_Error(
		'public_collaboration_cannot_create',
		__( 'Sorry, you are only allowed to work on the post you were invited to.', 'public-collaboration' ),
		[ 'status' => rest_authorization_required_code() ]
	);
}

/**
 * Adds a cron schedule for running every 15 minutes.
 *
 * @param array $schedules Cron schedules.
 * @return array Filtered cron schedules.
 *
 * @phpstan-param array<string, array{interval: int, display: string}> $schedules
 * @phpstan-return array<string, array{interval: int, display: string}>
 */
function filter_cron_schedules( array $schedules ): array {
	if ( ! isset( $schedules['public_collaboration_quarter_hourly'] ) ) {
		$schedules['public_collaboration_quarter_hourly'] = [
			'interval' => 15 * MINUTE_IN_SECONDS,
			'display'  => __( 'Every 15 Minutes', 'public-collaboration' ),
		];
	}

	return $schedules;
}

/**
 * Deletes collaboration requests that have expired, and the accounts they created.
 *
 * @return void
 */
function delete_expired_requests(): void {
	$posts = get_posts(
		[
			'post_type'        => Collaboration_Request::POST_TYPE,
			'post_status'      => 'publish',
			'numberposts'      => 100,
			'suppress_filters' => false,
			'meta_query'       => [ // phpcs:ignore WordPress.DB.SlowDBQuery.slow_db_query_meta_query
				[
					'key'     => Collaboration_Request::META_EXPIRES_AT,
					'value'   => time(),
					'compare' => '<=',
					'type'    => 'NUMERIC',
				],
			],
		]
	);

	foreach ( $posts as $post ) {
		$request = Collaboration_Request::from_post( $post );

		if ( $request instanceof Collaboration_Request ) {
			$request->delete();
		}
	}
}

/**
 * Plugin activation hook.
 *
 * @codeCoverageIgnore
 *
 * @return void
 */
function activate_plugin(): void {
	register_post_type();

	flush_rewrite_rules( false );

	if ( false === wp_next_scheduled( 'public_collaboration_cleanup' ) ) {
		wp_schedule_event( time(), 'public_collaboration_quarter_hourly', 'public_collaboration_cleanup' );
	}
}

/**
 * Plugin deactivation hook.
 *
 * @codeCoverageIgnore
 *
 * @return void
 */
function deactivate_plugin(): void {
	delete_expired_requests();

	unregister_post_type( Collaboration_Request::POST_TYPE );

	flush_rewrite_rules( false );

	$timestamp = wp_next_scheduled( 'public_collaboration_cleanup' );

	if ( false !== $timestamp ) {
		wp_unschedule_event( $timestamp, 'public_collaboration_cleanup' );
	}
}
